import type {
  Product,
  Category,
  Collection,
  InventoryItem,
  Order,
  Customer,
  Review,
  Discount,
  MediaAsset,
  ContentBlock,
  Page,
  NavigationMenu,
  StoreSettings,
  ThemeSettings,
  AdminUser,
  Role,
  ActivityLog,
} from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    title: 'Blush Floral Tiered Midi Dress',
    slug: 'blush-floral-tiered-midi-dress',
    shortDescription: 'Feminine chiffon midi dress featuring delicate vintage botanical prints.',
    description: '<p>Designed for breezy afternoon soirees and garden brunches. Crafted from ethereal georgette with a soft viscose lining, flutter cap sleeves, and a flattering cinch waist.</p>',
    sku: 'JQT-WMN-DRS-001',
    brand: 'JQ Trends',
    categoryIds: ['cat_dresses', 'cat_women'],
    collectionIds: ['col_new_arrivals', 'col_trending'],
    price: 1499,
    compareAtPrice: 2299,
    costPrice: 650,
    images: [
      { id: 'img_1', url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop', altText: 'Blush Floral Midi Dress Front View', isPrimary: true },
      { id: 'img_2', url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop', altText: 'Blush Floral Midi Dress Side Profile', isPrimary: false },
    ],
    variants: [
      { id: 'var_1_xs', sku: 'JQT-WMN-DRS-001-XS', title: 'XS / Blush Pink', price: 1499, stock: 12, options: { size: 'XS', color: 'Blush Pink' } },
      { id: 'var_1_s', sku: 'JQT-WMN-DRS-001-S', title: 'S / Blush Pink', price: 1499, stock: 24, options: { size: 'S', color: 'Blush Pink' } },
      { id: 'var_1_m', sku: 'JQT-WMN-DRS-001-M', title: 'M / Blush Pink', price: 1499, stock: 18, options: { size: 'M', color: 'Blush Pink' } },
      { id: 'var_1_l', sku: 'JQT-WMN-DRS-001-L', title: 'L / Blush Pink', price: 1499, stock: 8, options: { size: 'L', color: 'Blush Pink' } },
    ],
    status: 'published',
    tags: ['Floral', 'Midi Dress', 'Summer', 'Boutique', 'Women'],
    trackInventory: true,
    stock: 62,
    lowStockThreshold: 10,
    allowBackorders: false,
    seo: {
      title: 'Blush Floral Tiered Midi Dress | JQ Trends',
      description: 'Shop the designer Blush Floral Tiered Midi Dress in soft pastel blush. Free shipping above ₹999.',
      slug: 'blush-floral-tiered-midi-dress',
    },
    shipping: { weightKg: 0.35, isExpressAvailable: true },
    badges: { isFeatured: true, isNewArrival: true, isBestSeller: false },
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-25T14:30:00Z',
  },
  {
    id: 'prod_2',
    title: 'Rose Gold Zari Chanderi Kurti Set',
    slug: 'rose-gold-zari-chanderi-kurti-set',
    shortDescription: 'Regal silk blend Chanderi straight kurti adorned with handwoven rose gold zari borders.',
    description: '<p>A timeless tribute to festive elegance. Comes paired with matching cotton-silk trousers and a diaphanous organza dupatta with scalloped borders.</p>',
    sku: 'JQT-WMN-KRT-002',
    brand: 'JQ Trends',
    categoryIds: ['cat_kurtis', 'cat_women'],
    collectionIds: ['col_festive', 'col_trending'],
    price: 1899,
    compareAtPrice: 2899,
    costPrice: 850,
    images: [
      { id: 'img_3', url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop', altText: 'Rose Gold Chanderi Kurti Set Front', isPrimary: true },
      { id: 'img_4', url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop', altText: 'Zari Detail Close-up', isPrimary: false },
    ],
    variants: [
      { id: 'var_2_s', sku: 'JQT-WMN-KRT-002-S', title: 'S / Rose Gold', price: 1899, stock: 15, options: { size: 'S', color: 'Rose Gold' } },
      { id: 'var_2_m', sku: 'JQT-WMN-KRT-002-M', title: 'M / Rose Gold', price: 1899, stock: 20, options: { size: 'M', color: 'Rose Gold' } },
      { id: 'var_2_l', sku: 'JQT-WMN-KRT-002-L', title: 'L / Rose Gold', price: 1899, stock: 14, options: { size: 'L', color: 'Rose Gold' } },
      { id: 'var_2_xl', sku: 'JQT-WMN-KRT-002-XL', title: 'XL / Rose Gold', price: 1899, stock: 9, options: { size: 'XL', color: 'Rose Gold' } },
    ],
    status: 'published',
    tags: ['Festive', 'Chanderi', 'Kurti', 'Rose Gold', 'Ethnic'],
    trackInventory: true,
    stock: 58,
    lowStockThreshold: 10,
    allowBackorders: false,
    seo: {
      title: 'Rose Gold Zari Chanderi Kurti Set | JQ Trends',
      description: 'Festive pure Chanderi kurti set with handcrafted zari embroidery.',
      slug: 'rose-gold-zari-chanderi-kurti-set',
    },
    shipping: { weightKg: 0.5, isExpressAvailable: true },
    badges: { isFeatured: true, isNewArrival: false, isBestSeller: true },
    createdAt: '2026-08-21T11:00:00Z',
    updatedAt: '2026-08-26T09:15:00Z',
  },
  {
    id: 'prod_3',
    title: 'Dusty Rose Pleated Organza Saree',
    slug: 'dusty-rose-pleated-organza-saree',
    shortDescription: 'Contemporary ready-to-wear pleated organza saree with a pearl-embellished sweetheart blouse.',
    description: '<p>Sculptural modern draping meets romantic dusty rose sheen. Lightweight, effortlessly fluid, and wrinkle-resistant for gala evenings.</p>',
    sku: 'JQT-WMN-SRE-003',
    brand: 'JQ Trends',
    categoryIds: ['cat_sarees', 'cat_women'],
    collectionIds: ['col_festive', 'col_trending'],
    price: 2499,
    compareAtPrice: 3999,
    costPrice: 1100,
    images: [
      { id: 'img_5', url: 'https://images.unsplash.com/photo-1583391733975-021b33a0b800?w=800&auto=format&fit=crop', altText: 'Dusty Rose Organza Saree Drape', isPrimary: true },
    ],
    variants: [
      { id: 'var_3_fs', sku: 'JQT-WMN-SRE-003-FS', title: 'Free Size / Dusty Rose', price: 2499, stock: 25, options: { size: 'Free Size', color: 'Dusty Rose' } },
    ],
    status: 'published',
    tags: ['Saree', 'Organza', 'Dusty Rose', 'Wedding Guest', 'Festive'],
    trackInventory: true,
    stock: 25,
    lowStockThreshold: 5,
    allowBackorders: false,
    seo: {
      title: 'Dusty Rose Pleated Organza Saree | JQ Trends',
      description: 'Elevate your festive look with our modern pleated organza saree.',
      slug: 'dusty-rose-pleated-organza-saree',
    },
    shipping: { weightKg: 0.6, isExpressAvailable: true },
    badges: { isFeatured: false, isNewArrival: true, isBestSeller: false },
    createdAt: '2026-08-22T12:00:00Z',
    updatedAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'prod_4',
    title: 'Ivory & Blush Embroidered Co-ord Set',
    slug: 'ivory-blush-embroidered-co-ord-set',
    shortDescription: 'Tailored notched-collar blazer tunic paired with high-waisted palazzo pants in linen-cotton blend.',
    description: '<p>Clean minimalist silhouette with tone-on-tone resham embroidery on lapels and cuffs. Perfect balance of corporate chic and weekend brunch grace.</p>',
    sku: 'JQT-WMN-CRD-004',
    brand: 'JQ Trends',
    categoryIds: ['cat_coords', 'cat_women'],
    collectionIds: ['col_new_arrivals'],
    price: 1699,
    compareAtPrice: 2499,
    costPrice: 750,
    images: [
      { id: 'img_6', url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop', altText: 'Ivory & Blush Co-ord Set', isPrimary: true },
    ],
    variants: [
      { id: 'var_4_s', sku: 'JQT-WMN-CRD-004-S', title: 'S / Ivory Blush', price: 1699, stock: 18, options: { size: 'S', color: 'Ivory' } },
      { id: 'var_4_m', sku: 'JQT-WMN-CRD-004-M', title: 'M / Ivory Blush', price: 1699, stock: 14, options: { size: 'M', color: 'Ivory' } },
      { id: 'var_4_l', sku: 'JQT-WMN-CRD-004-L', title: 'L / Ivory Blush', price: 1699, stock: 7, options: { size: 'L', color: 'Ivory' } },
    ],
    status: 'published',
    tags: ['Co-ord', 'Linen', 'Ivory', 'Blush', 'Modern'],
    trackInventory: true,
    stock: 39,
    lowStockThreshold: 10,
    allowBackorders: false,
    seo: {
      title: 'Ivory & Blush Embroidered Co-ord Set | JQ Trends',
      description: 'Chic 2-piece tailored co-ord set with hand-finished embroidery.',
      slug: 'ivory-blush-embroidered-co-ord-set',
    },
    shipping: { weightKg: 0.45, isExpressAvailable: true },
    badges: { isFeatured: true, isNewArrival: true, isBestSeller: false },
    createdAt: '2026-08-23T14:00:00Z',
    updatedAt: '2026-08-26T11:00:00Z',
  },
  {
    id: 'prod_5',
    title: 'Girls Pastel Blossom Tulle Party Frock',
    slug: 'girls-pastel-blossom-tulle-party-frock',
    shortDescription: 'Whimsical multi-layered tulle party frock with 3D floral applique on satin bodice.',
    description: '<p>Crafted for birthday celebrations and wedding parties. 100% pure cotton inner lining ensures itch-free comfort and all-day twirl delight.</p>',
    sku: 'JQT-KDS-FRK-005',
    brand: 'JQ Trends Kids',
    categoryIds: ['cat_kids_girls', 'cat_kids'],
    collectionIds: ['col_kids', 'col_new_arrivals'],
    price: 1299,
    compareAtPrice: 1999,
    costPrice: 500,
    images: [
      { id: 'img_7', url: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop', altText: 'Girls Pastel Blossom Tulle Frock', isPrimary: true },
    ],
    variants: [
      { id: 'var_5_23', sku: 'JQT-KDS-FRK-005-23Y', title: '2-3 Years / Pastel Pink', price: 1299, stock: 15, options: { size: '2-3 Years', color: 'Pastel Pink' } },
      { id: 'var_5_45', sku: 'JQT-KDS-FRK-005-45Y', title: '4-5 Years / Pastel Pink', price: 1299, stock: 16, options: { size: '4-5 Years', color: 'Pastel Pink' } },
      { id: 'var_5_67', sku: 'JQT-KDS-FRK-005-67Y', title: '6-7 Years / Pastel Pink', price: 1299, stock: 10, options: { size: '6-7 Years', color: 'Pastel Pink' } },
    ],
    status: 'published',
    tags: ['Kids', 'Girls', 'Frock', 'Tulle', 'Party Wear'],
    trackInventory: true,
    stock: 41,
    lowStockThreshold: 10,
    allowBackorders: false,
    seo: {
      title: 'Girls Pastel Blossom Tulle Party Frock | JQ Trends',
      description: 'Comfortable & magical party frocks for girls with pure cotton inner lining.',
      slug: 'girls-pastel-blossom-tulle-party-frock',
    },
    shipping: { weightKg: 0.3, isExpressAvailable: true },
    badges: { isFeatured: true, isNewArrival: true, isBestSeller: true },
    createdAt: '2026-08-24T09:00:00Z',
    updatedAt: '2026-08-26T12:00:00Z',
  },
  {
    id: 'prod_6',
    title: 'Boys Heritage Silk Kurta & Nehru Jacket Set',
    slug: 'boys-heritage-silk-kurta-nehru-jacket-set',
    shortDescription: 'Regal 3-piece ethnic ensemble: raw silk kurta, woven jacquard Nehru jacket, and pyjama pants.',
    description: '<p>A dapper ethnic outfit for little princes during Diwali, weddings, and festivals. Features metallic coin buttons and breathable cotton-lining.</p>',
    sku: 'JQT-KDS-KRT-006',
    brand: 'JQ Trends Kids',
    categoryIds: ['cat_kids_boys', 'cat_kids'],
    collectionIds: ['col_kids', 'col_festive'],
    price: 1499,
    compareAtPrice: 2199,
    costPrice: 620,
    images: [
      { id: 'img_8', url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=800&auto=format&fit=crop', altText: 'Boys Heritage Silk Kurta Set', isPrimary: true },
    ],
    variants: [
      { id: 'var_6_34', sku: 'JQT-KDS-KRT-006-34Y', title: '3-4 Years / Cream & Blush', price: 1499, stock: 12, options: { size: '3-4 Years', color: 'Cream' } },
      { id: 'var_6_56', sku: 'JQT-KDS-KRT-006-56Y', title: '5-6 Years / Cream & Blush', price: 1499, stock: 14, options: { size: '5-6 Years', color: 'Cream' } },
      { id: 'var_6_78', sku: 'JQT-KDS-KRT-006-78Y', title: '7-8 Years / Cream & Blush', price: 1499, stock: 8, options: { size: '7-8 Years', color: 'Cream' } },
    ],
    status: 'published',
    tags: ['Kids', 'Boys', 'Kurta', 'Nehru Jacket', 'Ethnic'],
    trackInventory: true,
    stock: 34,
    lowStockThreshold: 10,
    allowBackorders: false,
    seo: {
      title: 'Boys Heritage Silk Kurta & Nehru Jacket Set | JQ Trends',
      description: 'Festive boys kurta pyjama set with jacquard Nehru jacket.',
      slug: 'boys-heritage-silk-kurta-nehru-jacket-set',
    },
    shipping: { weightKg: 0.4, isExpressAvailable: true },
    badges: { isFeatured: false, isNewArrival: false, isBestSeller: true },
    createdAt: '2026-08-24T10:00:00Z',
    updatedAt: '2026-08-26T13:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_women',
    name: "Women's Fashion",
    slug: 'women',
    description: 'Contemporary dresses, artisanal kurtis, sarees, and coordinated silhouettes.',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop',
    parentId: null,
    displayOrder: 1,
    isVisible: true,
    productCount: 4,
    seo: { title: "Women's Clothing & Dresses | JQ Trends", description: 'Shop modern luxury dresses, kurtis, and co-ords for women.' },
    children: [
      {
        id: 'cat_dresses',
        name: 'Dresses & Gowns',
        slug: 'women/dresses',
        parentId: 'cat_women',
        displayOrder: 1,
        isVisible: true,
        productCount: 2,
        seo: { title: "Women's Dresses & Gowns | JQ Trends" },
      },
      {
        id: 'cat_kurtis',
        name: 'Kurtis & Sets',
        slug: 'women/kurtis',
        parentId: 'cat_women',
        displayOrder: 2,
        isVisible: true,
        productCount: 1,
        seo: { title: 'Designer Kurtis & Sets | JQ Trends' },
      },
      {
        id: 'cat_coords',
        name: 'Co-ord Sets',
        slug: 'women/co-ords',
        parentId: 'cat_women',
        displayOrder: 3,
        isVisible: true,
        productCount: 1,
        seo: { title: 'Boutique Co-ord Sets | JQ Trends' },
      },
      {
        id: 'cat_sarees',
        name: 'Contemporary Sarees',
        slug: 'women/sarees',
        parentId: 'cat_women',
        displayOrder: 4,
        isVisible: true,
        productCount: 1,
        seo: { title: 'Organza & Silk Sarees | JQ Trends' },
      },
    ],
  },
  {
    id: 'cat_kids',
    name: 'Kids Collection',
    slug: 'kids',
    description: 'Charming festive attire and playful everyday wear for girls and boys.',
    imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop',
    parentId: null,
    displayOrder: 2,
    isVisible: true,
    productCount: 2,
    seo: { title: "Kids Clothing & Party Wear | JQ Trends", description: 'Playful and elegant kids fashion for boys and girls.' },
    children: [
      {
        id: 'cat_kids_girls',
        name: 'Girls Party Dresses',
        slug: 'kids/girls',
        parentId: 'cat_kids',
        displayOrder: 1,
        isVisible: true,
        productCount: 1,
        seo: { title: 'Girls Frocks & Party Dresses | JQ Trends' },
      },
      {
        id: 'cat_kids_boys',
        name: 'Boys Ethnic & Sets',
        slug: 'kids/boys',
        parentId: 'cat_kids',
        displayOrder: 2,
        isVisible: true,
        productCount: 1,
        seo: { title: 'Boys Kurta Sets & Jackets | JQ Trends' },
      },
    ],
  },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col_new_arrivals',
    title: 'New Arrivals Studio',
    slug: 'new-arrivals',
    description: 'Fresh boutique drops and curated seasonal silhouettes.',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop',
    type: 'automated',
    rules: [{ field: 'tag', operator: 'contains', value: 'Summer' }],
    productCount: 4,
    isVisible: true,
    displayOrder: 1,
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'col_trending',
    title: 'Trending Now',
    slug: 'trending-now',
    description: 'Our most-loved silhouettes trending across India.',
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop',
    type: 'manual',
    productIds: ['prod_1', 'prod_2', 'prod_3'],
    productCount: 3,
    isVisible: true,
    displayOrder: 2,
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'col_festive',
    title: 'Festive Elegance 2026',
    slug: 'festive-elegance',
    description: 'Zari, silk Chanderi, and organza craftsmanship.',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop',
    type: 'manual',
    productIds: ['prod_2', 'prod_3', 'prod_6'],
    productCount: 3,
    isVisible: true,
    displayOrder: 3,
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'col_kids',
    title: 'Little Twirls & Heritage',
    slug: 'kids-specials',
    description: 'Kids party frocks and festive kurtas.',
    imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop',
    type: 'manual',
    productIds: ['prod_5', 'prod_6'],
    productCount: 2,
    isVisible: true,
    displayOrder: 4,
    createdAt: '2026-08-20T10:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1001',
    orderNumber: 'JQT-847291',
    customer: {
      firstName: 'Aanya',
      lastName: 'Kapoor',
      email: 'aanya.kapoor@example.com',
      phone: '+91 98765 43210',
    },
    shippingAddress: {
      street: '124, 4th Cross, 100ft Road, Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560038',
      country: 'India',
    },
    items: [
      {
        id: 'item_1',
        productId: 'prod_1',
        productTitle: 'Blush Floral Tiered Midi Dress',
        variantTitle: 'M / Blush Pink',
        sku: 'JQT-WMN-DRS-001-M',
        imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=200&auto=format&fit=crop',
        price: 1499,
        quantity: 1,
        total: 1499,
      },
    ],
    subtotal: 1499,
    discountTotal: 0,
    shippingTotal: 0,
    taxTotal: 75,
    grandTotal: 1499,
    currency: 'INR',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    status: 'shipped',
    carrier: 'BlueDart Express',
    trackingNumber: 'BLUEDART-847291-BLR',
    trackingTimeline: [
      { stage: 'Order Placed & Confirmed', timestamp: '2026-08-26 10:15 AM', location: 'JQ Online', completed: true },
      { stage: 'Quality Inspected & Packed', timestamp: '2026-08-26 02:30 PM', location: 'Bengaluru Hub', completed: true },
      { stage: 'Dispatched via BlueDart', timestamp: '2026-08-26 06:45 PM', location: 'Indiranagar Hub', completed: true },
      { stage: 'Out for Delivery', timestamp: '2026-08-27 09:00 AM', location: 'Local Van', completed: false },
      { stage: 'Delivered', timestamp: 'Expected Today', location: 'Customer Doorstep', completed: false },
    ],
    adminNotes: ['Customer requested gift wrapping ribbon.', 'Express shipment priority tagged.'],
    placedAt: '2026-08-26T10:15:00Z',
    updatedAt: '2026-08-26T18:45:00Z',
  },
  {
    id: 'ord_1002',
    orderNumber: 'JQT-847290',
    customer: {
      firstName: 'Priya',
      lastName: 'Sharma',
      email: 'priya.sharma@example.com',
      phone: '+91 98234 56789',
    },
    shippingAddress: {
      street: 'Flat 402, Royal Palms, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400050',
      country: 'India',
    },
    items: [
      {
        id: 'item_2',
        productId: 'prod_2',
        productTitle: 'Rose Gold Zari Chanderi Kurti Set',
        variantTitle: 'S / Rose Gold',
        sku: 'JQT-WMN-KRT-002-S',
        imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=200&auto=format&fit=crop',
        price: 1899,
        quantity: 1,
        total: 1899,
      },
    ],
    subtotal: 1899,
    discountTotal: 0,
    shippingTotal: 0,
    taxTotal: 95,
    grandTotal: 1899,
    currency: 'INR',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    status: 'delivered',
    carrier: 'Delhivery',
    trackingNumber: 'DELHIVERY-774921-MUM',
    placedAt: '2026-08-24T14:30:00Z',
    updatedAt: '2026-08-26T11:00:00Z',
  },
  {
    id: 'ord_1003',
    orderNumber: 'JQT-847289',
    customer: {
      firstName: 'Sneha',
      lastName: 'Reddy',
      email: 'sneha.reddy@example.com',
      phone: '+91 97401 23456',
    },
    shippingAddress: {
      street: 'Plot 88, Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500033',
      country: 'India',
    },
    items: [
      {
        id: 'item_3',
        productId: 'prod_5',
        productTitle: 'Girls Pastel Blossom Tulle Party Frock',
        variantTitle: '4-5 Years / Pastel Pink',
        sku: 'JQT-KDS-FRK-005-45Y',
        imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=200&auto=format&fit=crop',
        price: 1299,
        quantity: 1,
        total: 1299,
      },
    ],
    subtotal: 1299,
    discountTotal: 0,
    shippingTotal: 0,
    taxTotal: 65,
    grandTotal: 1299,
    currency: 'INR',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    status: 'delivered',
    carrier: 'BlueDart Express',
    trackingNumber: 'BLUEDART-554109-HYD',
    placedAt: '2026-08-23T16:20:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    firstName: 'Aanya',
    lastName: 'Kapoor',
    email: 'aanya.kapoor@example.com',
    phone: '+91 98765 43210',
    ordersCount: 3,
    totalSpent: 4897,
    lastOrderAt: '2026-08-26T10:15:00Z',
    status: 'active',
    addresses: [
      {
        id: 'addr_1',
        type: 'home',
        street: '124, 4th Cross, 100ft Road, Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        postalCode: '560038',
        country: 'India',
        isDefault: true,
      },
    ],
    createdAt: '2026-07-15T08:00:00Z',
  },
  {
    id: 'cust_2',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@example.com',
    phone: '+91 98234 56789',
    ordersCount: 2,
    totalSpent: 3798,
    lastOrderAt: '2026-08-24T14:30:00Z',
    status: 'active',
    addresses: [
      {
        id: 'addr_2',
        type: 'home',
        street: 'Flat 402, Royal Palms, Bandra West',
        city: 'Mumbai',
        state: 'Maharashtra',
        postalCode: '400050',
        country: 'India',
        isDefault: true,
      },
    ],
    createdAt: '2026-07-20T12:00:00Z',
  },
  {
    id: 'cust_3',
    firstName: 'Sneha',
    lastName: 'Reddy',
    email: 'sneha.reddy@example.com',
    phone: '+91 97401 23456',
    ordersCount: 1,
    totalSpent: 1299,
    lastOrderAt: '2026-08-23T16:20:00Z',
    status: 'active',
    addresses: [
      {
        id: 'addr_3',
        type: 'home',
        street: 'Plot 88, Jubilee Hills',
        city: 'Hyderabad',
        state: 'Telangana',
        postalCode: '500033',
        country: 'India',
        isDefault: true,
      },
    ],
    createdAt: '2026-08-10T15:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    productId: 'prod_1',
    productTitle: 'Blush Floral Tiered Midi Dress',
    productImage: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=200&auto=format&fit=crop',
    customerName: 'Ananya Deshmukh',
    customerEmail: 'ananya.d@example.com',
    rating: 5,
    title: 'The fabric feels like pure luxury!',
    comment: 'Wore this for my sister’s mehendi brunch and got non-stop compliments. The blush pink tone is so soft and flattering.',
    isVerifiedBuyer: true,
    isFeatured: true,
    status: 'approved',
    createdAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'rev_2',
    productId: 'prod_2',
    productTitle: 'Rose Gold Zari Chanderi Kurti Set',
    productImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=200&auto=format&fit=crop',
    customerName: 'Rhea Sen',
    customerEmail: 'rhea.sen@example.com',
    rating: 5,
    title: 'Exquisite zari detailing!',
    comment: 'The craftsmanship on the Chanderi silk is outstanding. Fits true to size and arrived within 2 days in Indiranagar.',
    isVerifiedBuyer: true,
    isFeatured: true,
    status: 'approved',
    createdAt: '2026-08-24T15:30:00Z',
  },
  {
    id: 'rev_3',
    productId: 'prod_5',
    productTitle: 'Girls Pastel Blossom Tulle Party Frock',
    productImage: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=200&auto=format&fit=crop',
    customerName: 'Meera Nambiar',
    customerEmail: 'meera.n@example.com',
    rating: 5,
    title: 'My 4-year-old refused to take it off!',
    comment: 'So soft on the inside with the cotton lining. Beautiful pastel shades and high quality stitching.',
    isVerifiedBuyer: true,
    isFeatured: true,
    status: 'approved',
    createdAt: '2026-08-23T18:00:00Z',
  },
];

export const INITIAL_DISCOUNTS: Discount[] = [
  {
    id: 'disc_1',
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 999,
    maxDiscountAmount: 500,
    usageLimit: 1000,
    usageCount: 142,
    perCustomerLimit: 1,
    startAt: '2026-08-01T00:00:00Z',
    endAt: '2026-12-31T23:59:59Z',
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'disc_2',
    code: 'FESTIVE500',
    type: 'fixed_amount',
    value: 500,
    minOrderAmount: 2999,
    usageLimit: 500,
    usageCount: 68,
    startAt: '2026-08-15T00:00:00Z',
    endAt: '2026-10-30T23:59:59Z',
    isActive: true,
    createdAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'disc_3',
    code: 'FREESHIP',
    type: 'free_shipping',
    value: 0,
    minOrderAmount: 0,
    usageCount: 310,
    startAt: '2026-08-01T00:00:00Z',
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_MEDIA: MediaAsset[] = [
  {
    id: 'med_1',
    filename: 'hero-spring-festive.jpg',
    url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1920&auto=format&fit=crop',
    altText: 'Hero Spring Festive Editorial Lookbook',
    folder: 'Homepage',
    mimeType: 'image/jpeg',
    sizeBytes: 428000,
    width: 1920,
    height: 1080,
    usedInCount: 2,
    usedIn: ['Homepage Hero', 'Spring Lookbook Page'],
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'med_2',
    filename: 'blush-floral-midi-dress-1.jpg',
    url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=1000&auto=format&fit=crop',
    altText: 'Blush Floral Midi Dress Front View',
    folder: 'Women',
    mimeType: 'image/jpeg',
    sizeBytes: 312000,
    width: 1000,
    height: 1333,
    usedInCount: 3,
    usedIn: ['Product: Blush Floral Tiered Midi Dress', 'Trending Products Grid', 'Shop By Category'],
    createdAt: '2026-08-20T10:30:00Z',
  },
  {
    id: 'med_3',
    filename: 'rose-gold-chanderi-kurti-1.jpg',
    url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1000&auto=format&fit=crop',
    altText: 'Rose Gold Zari Chanderi Kurti Set',
    folder: 'Women',
    mimeType: 'image/jpeg',
    sizeBytes: 289000,
    width: 1000,
    height: 1333,
    usedInCount: 2,
    usedIn: ['Product: Rose Gold Zari Chanderi Kurti Set', "Women's Editorial Block"],
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'med_4',
    filename: 'girls-pastel-blossom-frock.jpg',
    url: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=1000&auto=format&fit=crop',
    altText: 'Girls Pastel Blossom Party Frock',
    folder: 'Kids',
    mimeType: 'image/jpeg',
    sizeBytes: 245000,
    width: 1000,
    height: 1333,
    usedInCount: 2,
    usedIn: ['Product: Girls Pastel Blossom Tulle Party Frock', 'Kids Editorial Showcase'],
    createdAt: '2026-08-20T11:30:00Z',
  },
  {
    id: 'med_5',
    filename: 'boys-heritage-silk-kurta.jpg',
    url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=1000&auto=format&fit=crop',
    altText: 'Boys Heritage Silk Kurta & Nehru Jacket',
    folder: 'Kids',
    mimeType: 'image/jpeg',
    sizeBytes: 380000,
    width: 1000,
    height: 1333,
    usedInCount: 1,
    usedIn: ['Product: Boys Heritage Silk Kurta & Nehru Jacket Set'],
    createdAt: '2026-08-20T12:00:00Z',
  },
];

export const INITIAL_HOMEPAGE_BLOCKS: ContentBlock[] = [
  {
    id: 'sec_hero_1',
    type: 'hero',
    name: 'Hero Banner Carousel',
    isVisible: true,
    displayOrder: 1,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      badge: 'SPRING / SUMMER 2026',
      title: 'Style That Speaks You',
      subtitle: 'Discover effortless grace, handcrafted elegance, and affordable luxury fashion for Women and Kids.',
      desktopImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1920&auto=format&fit=crop',
      mobileImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop',
      primaryCtaText: 'Explore Women',
      primaryCtaUrl: '/women',
      secondaryCtaText: 'Explore Kids',
      secondaryCtaUrl: '/kids',
      textAlignment: 'center',
      overlayOpacity: 40,
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_cat_grid_2',
    type: 'category-grid',
    name: 'Shop By Category Grid',
    isVisible: true,
    displayOrder: 2,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Shop By Category',
      subtitle: 'Curated silhouettes for every joyous occasion',
      categoryIds: ['cat_women', 'cat_kids', 'cat_dresses', 'cat_kurtis'],
      columns: 4,
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_trending_3',
    type: 'product-grid',
    name: 'Trending Products Showcase',
    isVisible: true,
    displayOrder: 3,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Trending Now',
      subtitle: 'Most desired boutique styles loved across India',
      collectionId: 'col_trending',
      limit: 4,
      columns: 4,
      ctaText: 'View All Trending',
      ctaUrl: '/collections/trending-now',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_womens_editorial_4',
    type: 'collection-banner',
    name: "Women's Luxury Editorial",
    isVisible: true,
    displayOrder: 4,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Timeless Grace & Modern Flair',
      subtitle: 'From flowing chiffon midi dresses to regal Chanderi silk kurti sets, embrace silhouettes tailored for timeless elegance.',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop',
      ctaText: "Shop Women's Edit",
      ctaUrl: '/women',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_new_arrivals_5',
    type: 'product-carousel',
    name: 'New Arrivals Carousel',
    isVisible: true,
    displayOrder: 5,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Fresh From the Studio',
      subtitle: 'New arrivals added every Friday',
      collectionId: 'col_new_arrivals',
      limit: 6,
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_kids_editorial_6',
    type: 'collection-banner',
    name: 'Kids Collection Editorial',
    isVisible: true,
    displayOrder: 6,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Little Stars, Big Style',
      subtitle: 'Pure cotton linings, itch-free seams, and joyful party frocks designed for pure childhood magic.',
      image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=1200&auto=format&fit=crop',
      ctaText: 'Shop Kids Collection',
      ctaUrl: '/kids',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_promo_banner_7',
    type: 'promo-banner',
    name: 'Festive Flash Promo Banner',
    isVisible: true,
    displayOrder: 7,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    schedule: {
      enabled: true,
      startDate: '2026-08-15T00:00:00Z',
      endDate: '2026-11-01T23:59:59Z',
    },
    data: {
      heading: 'Festive Grand Drop: Flat 15% Off',
      subtitle: 'Use code FESTIVE15 at checkout on orders above ₹2,499.',
      code: 'FESTIVE15',
      ctaText: 'Claim Offer',
      ctaUrl: '/sale',
      backgroundColor: '#CF9584',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_testimonials_8',
    type: 'testimonials',
    name: 'Customer Love & Reviews',
    isVisible: true,
    displayOrder: 8,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Loved by 50,000+ Fashion Lovers',
      subtitle: 'Real stories from verified boutique buyers',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_instagram_9',
    type: 'instagram',
    name: 'Instagram Social Lookbook',
    isVisible: true,
    displayOrder: 9,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Follow Us @JQTrendsOfficial',
      subtitle: 'Tag #JQTrends to get featured on our official lookbook',
      instagramHandle: 'JQTrendsOfficial',
      posts: [
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&auto=format&fit=crop',
      ],
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'sec_newsletter_10',
    type: 'newsletter',
    name: 'VIP Newsletter Club',
    isVisible: true,
    displayOrder: 10,
    visibilityDevice: { desktop: true, tablet: true, mobile: true },
    data: {
      heading: 'Join the JQ Trends Insider Club',
      subtitle: 'Receive private festive drop invites, early access sales, and ₹200 off your first order.',
      ctaText: 'Subscribe Now',
    },
    updatedAt: '2026-08-25T10:00:00Z',
  },
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  storeName: 'JQ Trends',
  tagline: 'Style That Speaks You — Women & Kids Fashion',
  contactEmail: 'care@jqtrends.com',
  phone: '+91 98765 43210',
  address: '124, 4th Cross, 100ft Road, Indiranagar, Bengaluru, Karnataka - 560038',
  currency: 'INR',
  timezone: 'Asia/Kolkata (IST)',
  shipping: {
    freeShippingThreshold: 999,
    standardRate: 99,
    expressRate: 199,
    codAvailable: true,
  },
  payments: {
    upiEnabled: true,
    cardsEnabled: true,
    netBankingEnabled: true,
    codEnabled: true,
  },
  tax: {
    gstEnabled: true,
    pricesIncludeTax: true,
    defaultGSTRate: 5,
  },
  social: {
    instagram: 'https://instagram.com/jqtrendsofficial',
    facebook: 'https://facebook.com/jqtrends',
    whatsapp: 'https://wa.me/919876543210',
    pinterest: 'https://pinterest.com/jqtrends',
    youtube: 'https://youtube.com/@jqtrends',
  },
  seo: {
    metaTitle: 'JQ Trends | Affordable Luxury Women & Kids Fashion',
    metaDescription: 'Shop exquisite women dresses, Chanderi kurtis, organza sarees, and kids festive party wear at JQ Trends.',
    ogImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop',
  },
};

export const INITIAL_THEME_SETTINGS: ThemeSettings = {
  template: 'jq-trends-luxury',
  colors: {
    primary: '#111111',
    accent: '#B77A68', // Rose Gold
    background: '#FAF6F2', // Soft Cream
    surface: '#FFFDFC',
    text: '#111111',
    textMuted: '#777777',
  },
  typography: {
    headingFont: 'Playfair Display',
    bodyFont: 'Plus Jakarta Sans',
  },
  buttonStyle: 'rounded',
  headerLayout: 'centered',
};

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'usr_demo',
    email: 'demo@mavenco.com',
    firstName: 'Demo',
    lastName: 'Merchant',
    roleId: 'role_owner',
    roleName: 'Store Owner',
    status: 'active',
    lastLoginAt: '2026-08-30T08:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'usr_superadmin',
    email: 'superadmin@mavenco.com',
    firstName: 'Super',
    lastName: 'Admin',
    roleId: 'role_owner',
    roleName: 'Platform Owner',
    status: 'active',
    lastLoginAt: '2026-08-30T08:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'usr_1',
    email: 'aanya.kapoor@example.com',
    firstName: 'Aanya',
    lastName: 'Kapoor',
    roleId: 'role_owner',
    roleName: 'Store Owner',
    status: 'active',
    lastLoginAt: '2026-08-27T08:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'usr_2',
    email: 'elena@auraliving.com',
    firstName: 'Elena',
    lastName: 'Rostova',
    roleId: 'role_owner',
    roleName: 'Store Owner',
    status: 'active',
    lastLoginAt: '2026-08-26T15:30:00Z',
    createdAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'usr_3',
    email: 'marcus@apexathletics.com',
    firstName: 'Marcus',
    lastName: 'Vance',
    roleId: 'role_owner',
    roleName: 'Store Owner',
    status: 'active',
    lastLoginAt: '2026-08-25T12:15:00Z',
    createdAt: '2026-08-15T00:00:00Z',
  },
];

export const INITIAL_ROLES: Role[] = [
  {
    id: 'role_owner',
    name: 'Super Admin / Owner',
    slug: 'owner',
    description: 'Full unrestricted platform access to all store settings, financial logs, and staff control.',
    isSystem: true,
    permissions: ['*'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'role_manager',
    name: 'Store Manager',
    slug: 'store-manager',
    description: 'Manage catalog, inventory, order processing, and customer relations.',
    isSystem: true,
    permissions: [
      'dashboard.read',
      'products.read', 'products.create', 'products.update', 'products.publish',
      'categories.read', 'categories.update',
      'inventory.read', 'inventory.update',
      'orders.read', 'orders.update', 'orders.fulfill',
      'customers.read', 'customers.update',
      'reviews.read', 'reviews.manage',
      'discounts.read', 'discounts.create', 'discounts.update',
    ],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'role_content',
    name: 'Content & Visual CMS Manager',
    slug: 'content-manager',
    description: 'Manage homepage sections, static pages, media assets, banners, navigation, and SEO.',
    isSystem: true,
    permissions: [
      'dashboard.read',
      'content.read', 'content.create', 'content.update', 'content.publish', 'content.delete',
      'media.read', 'media.upload', 'media.delete',
      'navigation.read', 'navigation.update',
      'marketing.read', 'marketing.manage',
    ],
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act_1',
    userEmail: 'aanya.kapoor@example.com',
    userName: 'Aanya Kapoor',
    action: 'content.homepage.published',
    entityType: 'homepage',
    entityId: 'hp_live',
    details: { version: 2, sectionsCount: 10, action: 'Published live to storefront' },
    ipAddress: '192.168.1.14',
    createdAt: '2026-08-27T08:02:00Z',
  },
  {
    id: 'act_2',
    userEmail: 'vikram.mehta@example.com',
    userName: 'Vikram Mehta',
    action: 'orders.status.updated',
    entityType: 'order',
    entityId: 'JQT-847291',
    details: { previousStatus: 'packed', newStatus: 'shipped', carrier: 'BlueDart Express' },
    ipAddress: '192.168.1.22',
    createdAt: '2026-08-26T18:45:00Z',
  },
  {
    id: 'act_3',
    userEmail: 'aanya.kapoor@example.com',
    userName: 'Aanya Kapoor',
    action: 'products.updated',
    entityType: 'product',
    entityId: 'prod_1',
    details: { price: 1499, title: 'Blush Floral Tiered Midi Dress' },
    ipAddress: '192.168.1.14',
    createdAt: '2026-08-26T14:30:00Z',
  },
  {
    id: 'act_4',
    userEmail: 'tanya.sharma@example.com',
    userName: 'Tanya Sharma',
    action: 'media.uploaded',
    entityType: 'media',
    entityId: 'med_1',
    details: { filename: 'hero-spring-festive.jpg', sizeKB: 428 },
    ipAddress: '192.168.1.45',
    createdAt: '2026-08-25T10:00:00Z',
  },
];
